<p> <center><img src="https://datascientest.fr/train/assets/logo_datascientest.png" style="height:200px"> </p>

<hr style="border-width:2px;border-color:#75DFC1">
<center><h1> Analyse et prédiction de la variabilité de la production solaire à partir de données ouvertes de la région PACA </h1></center>
<center><h2> Regroupement des variables au niveau régional </h2></center>
<hr style="border-width:2px;border-color:#75DFC1">

# I - Imports et récupération des données précédentes

Nous commencons par importer les librairies nécessaires pour manipuler nos données :

In [3]:
# Gestion des chemins
from pathlib import Path

# Données et calculs
import pandas as pd
import numpy as np

Puis on récupère les données collectées aux étapes précédentes :

In [4]:
# Chemin vers le répertoire de données d'entrée
input_path = Path('../../data/local_data/input/')

# Chemin vers le répertoire de résultats temporaires
temp_path = Path('../../data/local_data/temp/')

# Chemin vers le répertoire de résultats finaux
output_path = Path('../../data/local_data/output/')

# Chemin du dataset des communes sélectionnées 
communes = output_path / 'best_communes_geo_energy.csv'

In [5]:
# Charger les datasets
all_df = {
    'train' : pd.read_csv(temp_path / ('raw_train_5pts.csv'), index_col='datetime_utc', parse_dates=True),
    'valid' : pd.read_csv(temp_path / ('raw_valid_5pts.csv'), index_col='datetime_utc', parse_dates=True),
    'test' : pd.read_csv(temp_path / ('raw_test_5pts.csv'), index_col='datetime_utc', parse_dates=True)}

for df in all_df.values():
    display(df.head())

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite,tch_solaire_tp1,target,sin_hour,cos_hour,sin_doy,cos_doy
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2019-12-31 23:00:00+00:00,6123.0,0.0,0.0,0.0,335.596867,-67.454606,336.734433,-67.160776,337.561520,-68.097845,...,2.720,1.220,51.750,100.000,0.0,0.0,-0.258819,0.965926,-0.017213,0.999852
2019-12-31 23:30:00+00:00,5907.0,0.0,0.0,0.0,353.817769,-68.883102,354.738150,-68.485180,356.336005,-69.329403,...,2.760,1.405,54.215,98.790,0.0,0.0,-0.130526,0.991445,-0.017213,0.999852
2020-01-01 00:00:00+00:00,5724.0,0.0,0.0,0.0,12.883689,-68.564280,13.430816,-68.099948,15.637215,-68.757908,...,2.800,1.590,56.680,97.580,0.0,0.0,0.000000,1.000000,0.000000,1.000000
2020-01-01 00:30:00+00:00,5749.0,0.0,0.0,0.0,30.261125,-66.570892,30.451783,-66.089459,32.859299,-66.517353,...,2.675,1.635,33.325,96.065,0.0,0.0,0.130526,0.991445,0.000000,1.000000
2020-01-01 01:00:00+00:00,5700.0,0.0,0.0,0.0,44.631373,-63.284229,44.594428,-62.821307,46.883423,-63.030485,...,2.550,1.680,9.970,94.550,0.0,0.0,0.258819,0.965926,0.000000,1.000000

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite,tch_solaire_tp1,target,sin_hour,cos_hour,sin_doy,cos_doy
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00+00:00,4815.0,0.0,0.0,0.0,12.879512,-68.564229,13.426722,-68.099906,15.632999,-68.757915,...,2.710,1.440,99.410,96.430,0.0,0.0,0.000000,1.000000,0.0,1.0
2024-01-01 00:30:00+00:00,4853.0,0.0,0.0,0.0,30.257376,-66.571182,30.448105,-66.089748,32.855587,-66.517697,...,2.620,1.395,99.705,96.195,0.0,0.0,0.130526,0.991445,0.0,1.0
2024-01-01 01:00:00+00:00,4834.0,0.0,0.0,0.0,44.628236,-63.284768,44.591334,-62.821838,46.880350,-63.031066,...,2.530,1.350,100.000,95.960,0.0,0.0,0.258819,0.965926,0.0,1.0
2024-01-01 01:30:00+00:00,4964.0,0.0,0.0,0.0,56.102397,-59.130058,55.958833,-58.702637,57.998488,-58.727575,...,2.535,1.290,99.585,95.500,0.0,0.0,0.382683,0.923880,0.0,1.0
2024-01-01 02:00:00+00:00,4791.0,0.0,0.0,0.0,65.344202,-54.429271,65.169535,-54.042984,66.942140,-53.918107,...,2.540,1.230,99.170,95.040,0.0,0.0,0.500000,0.866025,0.0,1.0

,consommation,solaire,tco_solaire,tch_solaire,cru_azimuth,cru_altitude,sel_azimuth,sel_altitude,svt_azimuth,svt_altitude,...,eyg_temperature,eyg_vitesse_vent,eyg_nebulosite,eyg_humidite,tch_solaire_tp1,target,sin_hour,cos_hour,sin_doy,cos_doy
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00+00:00,5492.0,0.0,0.0,0.0,12.621973,-68.519484,13.173648,-68.055736,15.368659,-68.716819,...,3.26,1.000,96.43,93.350,0.0,0.0,0.000000,1.000000,0.0,1.0
2025-01-01 00:30:00+00:00,5498.0,0.0,0.0,0.0,30.001046,-66.548921,30.196673,-66.067425,32.597940,-66.499127,...,3.18,1.000,97.87,93.565,0.0,0.0,0.130526,0.991445,0.0,1.0
2025-01-01 01:00:00+00:00,5424.0,0.0,0.0,0.0,44.396127,-63.280642,44.362936,-62.817182,46.650081,-63.030109,...,3.10,1.000,99.31,93.780,0.0,0.0,0.258819,0.965926,0.0,1.0
2025-01-01 01:30:00+00:00,5506.0,0.0,0.0,0.0,55.899419,-59.138851,55.758234,-58.710650,57.798329,-58.738902,...,3.09,0.995,99.64,93.325,0.0,0.0,0.382683,0.923880,0.0,1.0
2025-01-01 02:00:00+00:00,5285.0,0.0,0.0,0.0,65.166910,-54.446690,64.993649,-54.059517,66.767626,-53.937514,...,3.08,0.990,99.97,92.870,0.0,0.0,0.500000,0.866025,0.0,1.0

# II - Regroupement au niveau régional

Nos jeux de données contiennent un **grand nombre de variables** (90 variables avant ajout de variables mémoires), en particuliers de variables collectées en cinq points différents. Comme on l'a vu, ces cinq points sont des points d'`intérêt régional` au niveau de la **région PACA**.

On se demande cependant si conserver cinq fois toutes ces variables ne va pas réduire les performances de notre future modélisation : c'est pourquoi on crée une version de nos jeux de données d'entrainement, de validation et de test

In [24]:
# On va créé un second dataset avec moins de colonnes
# en utilisant des moyennes pondérées sur les colonnes concernant les 5 points d'intérêts retenus

# Récupération de la base des noms de colonnes concernés
col_par_ville = []
# Comme tous les points d'intérêts ont exactement les même colonnes les concernant
# On fait une recherche des noms concernant la ville de Bras
for col in df.columns :
    if col[:3] == "bra":
        col_par_ville.append(col[4:])
print(col_par_ville)
print("Nombre de colonnes concernant chaque point d'intérêt :", len(col_par_ville))

['altitude', 'azimuth', 'bhi', 'bni', 'clear_sky_bhi', 'clear_sky_bni', 'clear_sky_dhi', 'clear_sky_ghi', 'dghi_dt', 'dghi_lag_1', 'dghi_lag_2', 'dghi_lag_3', 'dhi', 'dnebulosite_dt', 'dnebulosite_lag_1', 'dnebulosite_lag_2', 'ghi', 'ghi_lag_1', 'ghi_lag_2', 'ghi_mean_2h', 'ghi_mean_4h', 'ghi_std_2h', 'ghi_std_4h', 'humidite', 'nebulosite', 'nebulosite_lag_1', 'nebulosite_lag_2', 'temperature', 'toa', 'vitesse_vent']
Nombre de colonnes concernant chaque point d'intérêt : 30

In [25]:
# Récupération des coefficients de pondération
# Chargement du fichier contenant les communes représentatives
# et leur contribution énergétique associée
df_communes = pd.read_csv("../../data/local_data/01_Clustering/output/best_communes_geo_energy.csv")

# Affichage des noms de colonnes pour vérification
display(df_communes)

# Passsage du préfixe en minuscule
df_communes['prefix'] = df_communes['prefix'].str.lower() 

# Récupération des coefficients de pondération
coeff_ponderation = []
for poids in df_communes['poids'] :
    coeff_ponderation.append(poids)
print(coeff_ponderation)

# Calcul de la somme pondérée
for col in col_par_ville:
    col_name_region = f"region_{col}"
    df[col_name_region] = 0.0
    
    # Récupération de tous les noms des colonnes à pondérer
    all_concerns_cols = []
    for ville in df_communes['prefix'] :
        all_concerns_cols.append(f"{ville}_{col}")
    
    # Calcul
    for poids, ville in zip(coeff_ponderation, all_concerns_cols):
        df[col_name_region] = df[col_name_region] + poids * df[ville]
    
    # Supression des colonnes devenues inutiles
    df = df.drop(all_concerns_cols, axis=1)

print(f"Taille de df : {df.shape}")

,cluster_geo,best_commune,code_insee,lat,lon,energie_totale,poids,prefix
0,2,Cruis,4065,44.0845,5.8397,20356525.0,0.22,CRU
1,4,Saint-Étienne-le-Laus,5140,44.5075,6.1616,325158.0,0.06,SEL
2,0,Saint-Vallier-de-Thiey,6130,43.6994,6.8516,344281.0,0.07,SVT
3,1,Bras,83021,43.4723,5.9558,10603661.0,0.29,BRA
4,3,Eygalières,13034,43.7638,4.9554,1510927.0,0.36,EYG

[0.22, 0.06, 0.07, 0.29, 0.36]
Taille de df : (107589, 49)

In [26]:
# On enregistre 3 datasets pour train / valid / test
df[date_debut_train : date_fin_train].to_csv("../../data/train_region.csv")
df[date_debut_valid : date_fin_valid].to_csv("../../data/valid_region.csv")
df[date_debut_test : date_fin_test].to_csv("../../data/test_region.csv")

In [27]:
# Check
print("Train :")
df_train = pd.read_csv("../../data/train_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_train.head())
print("Taille du dataset :", df_train.shape)

print("\nValid :")
df_valid = pd.read_csv("../../data/valid_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_valid.head())
print("Taille du dataset :", df_valid.shape)

print("\nTest :")
df_test = pd.read_csv("../../data/test_region.csv", index_col='datetime_utc', parse_dates=True)
display(df_test.head())
print("Taille du dataset :", df_test.shape)

Train :

,consommation,cos_doy,cos_hour,sin_doy,sin_hour,solaire,target,target_lag_1,target_lag_2,target_lag_3,...,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_humidite,region_nebulosite,region_nebulosite_lag_1,region_nebulosite_lag_2,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2020-01-01 03:00:00+00:00,5332.0,1.0,0.707107,0.0,0.707107,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,73.3023,32.16660,19.95190,7.7372,3.36130,0.0,0.96980
2020-01-01 03:30:00+00:00,5219.0,1.0,0.608761,0.0,0.793353,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,72.5645,32.21870,32.16660,19.9519,3.26355,0.0,0.97035
2020-01-01 04:00:00+00:00,5157.0,1.0,0.500000,0.0,0.866025,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,71.8267,32.27080,32.21870,32.1666,3.16580,0.0,0.97090
2020-01-01 04:30:00+00:00,5161.0,1.0,0.382683,0.0,0.923880,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,70.5524,32.58025,32.27080,32.2187,3.22595,0.0,0.98650
2020-01-01 05:00:00+00:00,5108.0,1.0,0.258819,0.0,0.965926,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,69.2781,32.88970,32.58025,32.2708,3.28610,0.0,1.00210

Taille du dataset : (70122, 49)

Valid :

,consommation,cos_doy,cos_hour,sin_doy,sin_hour,solaire,target,target_lag_1,target_lag_2,target_lag_3,...,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_humidite,region_nebulosite,region_nebulosite_lag_1,region_nebulosite_lag_2,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2024-01-01 00:00:00+00:00,4812.0,1.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,96.33220,91.8536,88.0609,84.2682,2.66020,0.0,2.47700
2024-01-01 00:30:00+00:00,4833.0,1.0,0.991445,0.0,0.130526,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,95.95980,94.0952,91.8536,88.0609,2.58245,0.0,2.45855
2024-01-01 01:00:00+00:00,4863.0,1.0,0.965926,0.0,0.258819,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,95.58740,96.3368,94.0952,91.8536,2.50470,0.0,2.44010
2024-01-01 01:30:00+00:00,4903.0,1.0,0.923880,0.0,0.382683,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,95.19045,97.7836,96.3368,94.0952,2.47905,0.0,2.39285
2024-01-01 02:00:00+00:00,4737.0,1.0,0.866025,0.0,0.500000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,94.79350,99.2304,97.7836,96.3368,2.45340,0.0,2.34560

Taille du dataset : (17568, 49)

Test :

,consommation,cos_doy,cos_hour,sin_doy,sin_hour,solaire,target,target_lag_1,target_lag_2,target_lag_3,...,region_ghi_mean_4h,region_ghi_std_2h,region_ghi_std_4h,region_humidite,region_nebulosite,region_nebulosite_lag_1,region_nebulosite_lag_2,region_temperature,region_toa,region_vitesse_vent
datetime_utc,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00+00:00,5277.0,1.0,1.000000,0.0,0.000000,0.0,0.0,0.0,-0.04,0.00,...,0.0,0.0,0.0,85.42900,68.10510,64.53005,60.95500,3.7956,0.0,0.7248
2025-01-01 00:30:00+00:00,5314.0,1.0,0.991445,0.0,0.130526,0.0,0.0,0.0,0.00,-0.04,...,0.0,0.0,0.0,85.57575,67.91415,68.10510,64.53005,3.7172,0.0,0.7478
2025-01-01 01:00:00+00:00,5262.0,1.0,0.965926,0.0,0.258819,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,85.72250,67.72320,67.91415,68.10510,3.6388,0.0,0.7708
2025-01-01 01:30:00+00:00,5287.0,1.0,0.923880,0.0,0.382683,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,85.41155,69.23185,67.72320,67.91415,3.6087,0.0,0.7865
2025-01-01 02:00:00+00:00,5070.0,1.0,0.866025,0.0,0.500000,0.0,0.0,0.0,0.00,0.00,...,0.0,0.0,0.0,85.10060,70.74050,69.23185,67.72320,3.5786,0.0,0.8022

Taille du dataset : (19899, 49)