<p> <center><img src="https://datascientest.fr/train/assets/logo_datascientest.png" style="height:200px"> </p>

<hr style="border-width:2px;border-color:#75DFC1">
<center><h1> Analyse et prédiction de la variabilité de la production solaire à partir de données ouvertes de la région PACA </h1></center>
<center><h2> Collecte de nouvelles données </h2></center>
<hr style="border-width:2px;border-color:#75DFC1">

Au début du projet, nous avons collecté les données mises à disposition par RTE dans le dataset **éCO2mix** : ces données s'arrétaient en 2024. Depuis, l'année **2025 ainsi que les premiers mois de 2026** sont disponibles. 

Ce notebook propose une collecte des nouvelles données pour les concaténer aux anciennes.

# I - Acquisition des données de RTE

On peut trouver les nouvelles données brutes sur le site Internet de **RTE** (https://www.rte-france.com/donnees-publications/eco2mix-donnees-temps-reel/telecharger-indicateurs).

On a préalablement téléchargé ces données et on les a placées dans un répertoire de travail dont on stocke le chemin dans une variable `input_datasets`. Les résultats intermédiaires et finaux seront stockés dans `output_datasets`.

In [4]:
# Répertoire des données d'éCO2mix téléchargées
input_datasets = '../../data/local_data/02_Collecte_datasets/05_annees_2025_2026/input/'

# Répertoire où seront stockés les résultats
output_datasets = '../../data/local_data/02_Collecte_datasets/05_annees_2025_2026/output/'

In [2]:
# Importer des librairies usuelles pour traiter des datasets
import pandas as pd
import numpy as np

# Importer une librairie pour traiter des fichiers zip
from zipfile import ZipFile

On va extraire l'archive téléchargée qui contient les données des années 2025 et début 2026 :

In [5]:
# Récupération du chemin de l'archive à décompresser
chemin_dataset_2025_26 = input_datasets + 'eCO2mix_RTE_PACA_En-cours-TR'

# Décompresser l'archive pour récupérer 
with ZipFile(chemin_dataset_2025_26 + '.zip', 'r') as zip_file :
        zip_file.printdir()
        zip_file.extractall(input_datasets)

File Name                                             Modified             Size
eCO2mix_RTE_PACA_En-cours-TR.xls               2026-02-19 13:21:32      9091679

In [7]:
# Observer les premières lignes du dataset le plus ancien (correspond à l'année 2013) :
print("\nJeu de données 2025-2026 :")

## Lire le jeu de données
df = pd.read_csv(chemin_dataset_2025_26 + '.xls', sep='\t', encoding='latin_1')

## Afficher les premières lignes
display(df.head())

## Afficher les dernières lignes
display(df.tail())

## Afficher la taille du dataset
print(f"Nombre de colonnes du jeu de données 2025-2026 : {df.shape[1]}.")

Jeu de données 2025-2026 :

/tmp/ipykernel_17677/296983369.py:5: DtypeWarning: Columns (17,26,29,38,44,51,55,57,59,61,63,65) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_dataset_2025_26 + '.xls', sep='\t', encoding='latin_1')

,Périmètre,Nature,Date,Heures,Consommation,Thermique,Nucléaire,Eolien,Solaire,Hydraulique,...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Unnamed: 67
0,PACA,Données temps réel,2025-01-01,00:00,5583.0,634.0,0.0,1.0,0.0,571.0,...,ND,0.02,1.04,0.0,0.0,10.23,17.68,1.45,27.27,NaN
1,PACA,Données temps réel,2025-01-01,00:15,5532.0,453.0,0.0,1.0,0.0,721.0,...,ND,0.02,1.04,0.0,0.0,13.03,22.33,1.45,26.94,NaN
2,PACA,Données temps réel,2025-01-01,00:30,5430.0,390.0,0.0,2.0,0.0,717.0,...,ND,0.04,2.08,0.0,0.0,13.2,22.21,1.47,26.94,NaN
3,PACA,Données temps réel,2025-01-01,00:45,5321.0,391.0,0.0,1.0,0.0,721.0,...,ND,0.02,1.04,0.0,0.0,13.55,22.33,1.47,26.26,NaN
4,PACA,Données temps réel,2025-01-01,01:00,5277.0,206.0,0.0,2.0,0.0,720.0,...,ND,0.04,2.08,0.0,0.0,13.64,22.30,1.48,26.26,NaN

,Périmètre,Nature,Date,Heures,Consommation,Thermique,Nucléaire,Eolien,Solaire,Hydraulique,...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Unnamed: 67
39836,PACA,Données temps réel,2026-02-19,23:00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39837,PACA,Données temps réel,2026-02-19,23:15,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39838,PACA,Données temps réel,2026-02-19,23:30,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39839,PACA,Données temps réel,2026-02-19,23:45,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39840,RTE ne pourra Ãªtre tenu responsable de l'usag...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Nombre de colonnes du jeu de données 2025-2026 : 68.

On remarque que ce nouveau dataset présente des mesures toutes les 15 minutes alors que dans nos précédents jeux de données d'éCO2mix les mesures n'avaient lieu que toutes les 30 minutes. Pour conserver la cohérence entre l'ancien et le nouveau jeu de donnée, on va devoir supprimer une mesure sur deux.

Concernant l'année 2026, on remarque que les dernières lignes concernant le jour où les données ont été téléchargées sont manquantes : des lignes ont été créées pour cette journée jusqu'à minuit, mais les dernières sont dans le futur par rapport à l'heure d'extraction, d'où les valeurs manquantes observées.

On va :
- ne garder que les colonnes que nous avions conservées dans le premier jeu de données ;
- supprimer les observations où la variable `TCH Solaire (%)` est absente (ce qui nous permet d'éliminer les observations dans le futur par rapport à l'extraction ainsi que la dernière ligne qui est un disclaimer) ;
- supprimer une ligne sur deux pour avoir la même résolution temporelle que dans le premier jeu de données.

## A - Sélection des colonnes

In [8]:
# Liste des variables d'éCO2mix retenues dans l'ancien dataset
variables_retenues = ['Périmètre', 'Nature', 'Date', 'Heures', 
                      'Consommation', 'Solaire', 'Ech. physiques', 
                      'Stockage batterie', 'Déstockage batterie', 
                      'TCO Solaire (%)', 'TCH Solaire (%)']

# Vérification de la présence de ces variables dans le nouveau dataset
toutes_presentes = True
for var in variables_retenues :
    if var not in df.columns :
        toutes_presentes = False

print("Les variables précédemment retenues sont-elles toutes présentes dans le nouveau dataset ?", toutes_presentes)

Les variables précédemment retenues sont-elles toutes présentes dans le nouveau dataset ? True

In [10]:
# Les variables étant toutes présentes, on peut procéder à leur extraction
print("Dimensions du dataset avant réduction du nombre de variables :", df.shape)
df = df[variables_retenues]
print("Dimensions du dataset après réduction du nombre de variables :", df.shape)

Dimensions du dataset avant réduction du nombre de variables : (39841, 68)
Dimensions du dataset après réduction du nombre de variables : (39841, 11)

## B - Suppression des observations inutiles

Les observations ne contenant pas la variable `TCH Solaire (%)` ne permettront pas de calculer la variable cible de variation de production : on les retire du dataset.

In [12]:
# On supprime les lignes où la variable TCH Solaire est manquante
df = df.dropna(subset=['TCH Solaire (%)'])

On vérifie s'il reste des valeurs manquantes :

In [13]:
print(df.isna().sum())

Périmètre              0
Nature                 0
Date                   0
Heures                 0
Consommation           0
Solaire                0
Ech. physiques         0
Stockage batterie      0
Déstockage batterie    0
TCO Solaire (%)        0
TCH Solaire (%)        0
dtype: int64

## C - Résolution temporelle

On supprime une observation sur deux pour conserver la même résolution temporelle que précédemment.